AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Haya App

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ping/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  PingApi:
    Description: API Gateway endpoint URL for Prod stage for Ping function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping/"
  PingFunction:
    Description: Ping Lambda Function ARN
    Value: !GetAtt PingFunction.Arn
  PingFunctionIamRole:
    Description: Implicit IAM Role created for Ping function
    Value: !GetAtt PingFunctionRole.Arn
