name: Go

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: setup task
        uses: arduino/setup-task@v2
      
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      
      - name: testing
        run: task test
      
      - name: coverage report
        uses: ncruces/go-coverage-report@v0.3.0
