name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Go coverage report
        uses: ncruces/go-coverage-report@v0.3.0
